# Generated by Django 3.2.12 on 2022-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_title',
        ),
    ]
